### PR TITLE
Perform bulk uploads as a series of smaller requests

### PR DESCRIPTION
**Pull request by czan**
When I upload a batch of photos/videos in one hit I keep hitting the max request size limit on my nginx reverse proxy. I don't want to raise the limit, and it seems like doing bulk uploads in one big request causes other issues (e.g. #72).

As far as I can tell, the upload process blocks the UI, so this PR assumes that and doesn't try to handle multiple batches being started at different times. I think the class needs a more significant refactor if we want to handle that case. The error case is also a bit blunt, and doesn't provide useful feedback in the partial failure case, when some photos succeeded and others failed. There's a lot of room for improvement, but I wanted to start with the minimal changes that would work for my use.

Looking at [the PhotoPrism server code](https://github.com/photoprism/photoprism/blob/develop/internal/api/upload.go#L59) I'm not expecting any problems, and in my manual testing things have worked as expected.

### CODE REVIEW

**Comment by benmccann** [comment]
It looks like the CI is failing because of https://github.com/photoprism/photoprism-mobile/issues/84, which was just fixed. If you rebase against `master` hopefully it should pass

**Comment by benmccann** [comment]
It looks like CI is now failing on a line changed in this PR:

>$ flutter analyze
info • Specify type annotations • lib/common/photoprism_uploader.dart:178:18 • always_specify_types

**Comment by czan** [comment]
Sorry about that. I've added the type, so `flutter analyze` now reports "No issues found!" locally. Hopefully CI will pass, too!

**Comment by thielepaul** [comment]
Probably the manual upload should be refactored to share as much code as possible with the automatic upload. Then, it would not need to block the UI and would resume in background if you close the app.

**Review by thielepaul — APPROVED** [review]

**Pull request merged**
