### PR TITLE
Filter and sort dialog rework

### PR DESCRIPTION
**Pull request by osiris86**
I did this in preparation for a sectioned photos page. I wanted to provide options to group the photos by day, month or not at all. Later I realised the grouping is a bit more work than I thought :D

I added options to the action bar to switch between different lists to display (default, archive, private). I removed the selection boxes in the sort and filter dialog and inserted radio buttons.

I'm not happy with the wording of the "default" list, so I'm open for suggestions :)

Will hopefully add the sectioned grid view with a later PR.

### CODE REVIEW

**Comment by thielepaul** [comment]
thanks for your contribution!

can you please check that the CI passes then I will take a look at it: https://github.com/photoprism/photoprism-mobile/pull/114/checks

**Comment by osiris86** [comment]
Thanks, I've fixed the CI checks.

**Comment by thielepaul** [comment]
I just remembered #98, @mrrsm what do you think about this MR?

**Comment by osiris86** [comment]
Oh, I see... I wasn't aware of this. 
Personally I still think that the approach of separate lists is more clear. It's also more consistent with the web UI. 

Another suggestion: Keeping the "default" and "archive" list and removing the "private" list. Change the FilterPhotosDialog so that it has four sections:
* Sort 
    * Update At
    * Taken At
    * ...
* Sort order
    * Ascending
    * Descending
* Show types
    * Image
    * Live
    * Video
* Display settings
    * Show private Photos
    * possibly more options in the future, e.g. "local photos" (#100 ;-) )

**Comment by mrrsm** [comment]
> It's also more consistent with the web UI.

I'm not sold on the web UI and mobile UI even needing to match as they are different enough platforms and are viewed differently.  However, I do agree having separate lists is more clear.

As long as the functionality is there and not extremely obtuse to find I'm all for any change that allows someone to better customize the filters.

**Pull request merged**
